source 'https://rubygems.org'

ruby '>= 3.2.0'

gem 'cocoapods', '~> 1.16'
gem 'xcpretty', '~> 0.4'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
